# Generated by Django 4.2.6 on 2023-10-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_cart_complete_cart_completed_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='completed',
            new_name='complete',
        ),
    ]
